### ISSUE TITLE
Infinite looping logic gates

### ISSUE THREAD

**Issue by Ghoose1** [Ved-s/TerraLogic#1]
When I have a logic gate wired as show in the image and activate the switch, it will crash the program unless the simulation is paused, in which case it will infinitely loop between turning itself off and on when the step button is used. 
<img width="145" alt="image" src="https://user-images.githubusercontent.com/78841748/184519652-c041bc07-f39a-4930-9710-39aa052d4926.png">

If this were to be made in-game, the gate would fire once then give smoke particles, as they can only change state once per frame, which isn't a thing in the simulation.

**Comment by Ved-s** [comment]
Won't be fixed soon - I have internet problems and can't push to GitHub, but I'll try to fix this again
